import { SyndicateMember } from '../types';


export const RELATIONSHIP_TREE: SyndicateMember[] = [
  // --- BOSS ---
  {
    id: 'father',
    name: 'FATHER',
    role: 'BOSS',
    position: { x: 50, y: 10 },
    status: 'ACTIVE',
    phase: 1,
    chapter: 6,
    description: 'The Patriarch',
    materialType: 'polaroid'
  },
  // --- UNDERBOSS ---
  {
    id: 'the_mother',
    name: 'THE MOTHER',
    role: 'UNDERBOSS',
    parentId: 'father',
    position: { x: 40, y: 20 },
    status: 'ACTIVE',
    phase: 1,
    chapter: 6,
    description: 'Matriarch',
    materialType: 'polaroid'
  },
  // --- LIEUTENANTS ---
  {
    id: 'conchar',
    name: 'CONCHAR',
    role: 'LIEUTENANT',
    parentId: 'father',
    position: { x: 25, y: 40 },
    status: 'MISSING',
    phase: 1,
    chapter: 1,
    description: 'Eldest Son / Enforcer',
    materialType: 'document'
  },
  {
    id: 'luciano',
    name: 'LUCIANO',
    role: 'LIEUTENANT',
    parentId: 'father',
    position: { x: 50, y: 40 },
    status: 'DECEASED',
    phase: 1,
    chapter: 3,
    description: 'Finance / Distribution',
    materialType: 'polaroid'
  },
  {
    id: 'lundgren',
    name: 'LUNDGREN',
    role: 'LIEUTENANT',
    parentId: 'father',
    position: { x: 75, y: 40 },
    status: 'ARRESTED',
    phase: 1,
    chapter: 3,
    description: 'Cult Leader',
    materialType: 'clipping'
  },
  {
    id: 'silas',
    name: 'SILAS',
    role: 'LIEUTENANT',
    parentId: 'father',
    position: { x: 60, y: 20 },
    status: 'DECEASED',
    phase: 1,
    chapter: 4,
    description: 'Second Son',
    materialType: 'polaroid'
  },
  // --- SOLDIERS / ASSOCIATES ---
  {
    id: 'nibi',
    name: 'NIBI',
    role: 'SOLDIER',
    parentId: 'conchar',
    position: { x: 25, y: 70 },
    status: 'DECEASED',
    phase: 1,
    chapter: 1,
    description: 'The Scapegoat? (1971)',
    materialType: 'sketch'
  },
  {
    id: 'morning',
    name: 'MORNING',
    role: 'ASSOCIATE',
    parentId: 'conchar',
    position: { x: 38, y: 65 },
    status: 'ACTIVE',
    phase: 1,
    description: 'Bar owner / Fence',
    chapter: 1,
    materialType: 'polaroid'
  },
  {
    id: 'roger_beebe',
    name: 'ROGER BEEBE',
    role: 'ASSOCIATE',
    parentId: 'lundgren',
    position: { x: 75, y: 70 },
    status: 'ARRESTED',
    phase: 1,
    chapter: 1,
    description: 'Confessed to 1968 crimes',
    materialType: 'document'
  },
  {
    id: 'little_derek_wayne',
    name: 'DEREK WAYNE JR.',
    role: 'ASSOCIATE',
    parentId: 'father',
    position: { x: 80, y: 30 },
    status: 'DECEASED',
    phase: 1,
    description: 'Family Massacre Victim',
    chapter: 1,
    materialType: 'clipping'
  },
  {
    id: 'capone',
    name: 'R. CAPONE',
    role: 'ASSOCIATE',
    parentId: 'conchar',
    position: { x: 15, y: 55 },
    status: 'MISSING',
    phase: 1,
    description: 'Deep Cover / "Orphan"',
    chapter: 1,
    materialType: 'polaroid'
  },
  {
    id: 'martha_diaz',
    name: 'MARTHA DIAZ',
    role: 'ASSOCIATE',
    parentId: 'conchar',
    position: { x: 80, y: 80 },
    status: 'DECEASED',
    phase: 1,
    description: 'Laundromat Victim',
    chapter: 2,
    materialType: 'clipping'
  },
  {
    id: 'aw_wilmo',
    name: 'A.W. WILMER',
    role: 'ASSOCIATE',
    parentId: 'conchar',
    position: { x: 85, y: 70 },
    status: 'ARRESTED',
    phase: 1,
    description: 'The Scapegoat? (1990)',
    chapter: 2,
    materialType: 'document'
  },
  {
    id: 'arthur_dawson',
    name: 'ARTHUR DAWSON',
    role: 'ASSOCIATE',
    parentId: 'father',
    position: { x: 10, y: 20 },
    status: 'ACTIVE',
    phase: 1,
    description: 'Key witness',
    chapter: 2,
    materialType: 'document'
  },
  {
    id: 'julie',
    name: 'JULIE',
    role: 'ASSOCIATE',
    parentId: 'conchar',
    position: { x: 60, y: 85 },
    status: 'DECEASED',
    phase: 1,
    chapter: 3,
    description: 'Frozen Child',
    materialType: 'clipping'
  },
  {
    id: 'jc_penney',
    name: 'JC PENNEY',
    role: 'ASSOCIATE',
    parentId: 'father',
    position: { x: 90, y: 60 },
    status: 'ACTIVE',
    phase: 1,
    chapter: 3,
    description: 'Department Store / Target',
    materialType: 'clipping'
  },
  {
    id: 'juvell_chambers',
    name: 'JUVELL CHAMBERS',
    role: 'SOLDIER',
    parentId: 'father',
    position: { x: 10, y: 40 },
    status: 'ACTIVE',
    phase: 1,
    chapter: 3,
    description: 'Ex-Cop / Recruit',
    materialType: 'document'
  },
  {
    id: 'boris_smirnov',
    name: 'BORIS SMIRNOV',
    role: 'SOLDIER',
    parentId: 'father',
    position: { x: 90, y: 40 },
    status: 'ARRESTED',
    phase: 1,
    chapter: 3,
    description: 'Burkesville Gang',
    materialType: 'document'
  },
  {
    id: 'cynthia_miller',
    name: 'CYNTHIA MILLER',
    role: 'ASSOCIATE',
    parentId: 'silas',
    position: { x: 70, y: 15 },
    status: 'MISSING',
    phase: 1,
    description: 'Static Snow Victim',
    chapter: 3,
    materialType: 'clipping'
  },
  {
    id: 'vanessa',
    name: 'VANESSA',
    role: 'ASSOCIATE',
    parentId: 'the_mother',
    position: { x: 30, y: 30 },
    status: 'ACTIVE',
    phase: 1,
    description: 'Adopted Daughter',
    chapter: 4,
    materialType: 'polaroid'
  },
  {
    id: 'peter_henderson',
    name: 'PETER HENDERSON',
    role: 'ASSOCIATE',
    parentId: 'conchar',
    position: { x: 20, y: 80 },
    status: 'DECEASED',
    phase: 1,
    description: 'Davenport Victim',
    chapter: 4,
    materialType: 'clipping'
  },
  {
    id: 'richie_dreyfuss',
    name: 'RICHIE DREYFUSS',
    role: 'SOLDIER',
    parentId: 'conchar',
    position: { x: 40, y: 80 },
    status: 'DECEASED',
    phase: 1,
    description: 'The "Loser" / Failed Recruit',
    chapter: 4,
    materialType: 'document'
  },
  {
    id: 'priest',
    name: 'THE PRIEST',
    role: 'ASSOCIATE',
    parentId: 'lundgren',
    position: { x: 85, y: 50 },
    status: 'MISSING',
    phase: 1,
    description: 'Texarkana Connection',
    chapter: 5,
    materialType: 'polaroid'
  },
  {
    id: 'alexei',
    name: 'ALEXEI ROCKOVICH',
    role: 'SOLDIER',
    parentId: 'father',
    position: { x: 50, y: 60 },
    status: 'DECEASED',
    phase: 1,
    description: 'Soviet Connection',
    chapter: 5,
    materialType: 'document'
  },
  {
    id: 'morandi',
    name: 'MORANDI',
    role: 'ASSOCIATE',
    parentId: 'father',
    position: { x: 60, y: 70 },
    status: 'ARRESTED',
    phase: 1,
    chapter: 5,
    description: 'Chemist / Bomber',
    materialType: 'document'
  },
  {
    id: 'john_morrissey',
    name: 'JOHN MORRISSEY',
    role: 'ASSOCIATE',
    parentId: 'father',
    position: { x: 70, y: 80 },
    status: 'DECEASED',
    phase: 1,
    description: 'St. Louis Victim',
    chapter: 5,
    materialType: 'clipping'
  },
  {
    id: 'dr_reggie',
    name: 'DR. REGGIE',
    role: 'HANDLER',
    position: { x: 10, y: 10 },
    status: 'ACTIVE',
    phase: 2,
    description: 'Handler / Architect?',
    chapter: 6,
    materialType: 'document'
  },
  {
    id: 'felipe_maldonado',
    name: 'FELIPE MALDONADO',
    role: 'ASSOCIATE',
    parentId: 'father',
    position: { x: 20, y: 60 },
    status: 'DECEASED',
    phase: 1,
    chapter: 4,
    description: 'Band Leader / Poster Figure',
    materialType: 'clipping'
  },
  {
    id: 'william_dawson',
    name: 'WILLIAM DAWSON',
    role: 'ASSOCIATE',
    parentId: 'father',
    position: { x: 5, y: 30 },
    status: 'DECEASED',
    phase: 1,
    chapter: 2,
    description: 'The Timberman / Libby Town Patriarch',
    materialType: 'polaroid'
  }
];

export const CONFESSION_REGISTRY = [
  {
    id: 'confession_1',
    displayId: 'REC-1971-MN',
    title: '供述 No.1: 缅因州银行劫案',
    eventTime: '1971',
    location: '缅因州 (Maine)',
    keywords: ['缅因州', '阿尔衮琴', '供述', '扭曲关系'],
    people: ['雷吉博士 (Dr. Reggie)', '尼比 (Nibi)', '康查尔 (Conchar)'],
    summary: '关于1971年针对缅因州第一国民银行的武装劫案供述。揭示了尼比作为执行者与康查尔作为策划者之间的非典型同谋关系。',
    status: 'DECRYPTED'
  },
  {
    id: 'confession_2',
    displayId: 'REC-1968-OH',
    title: '供述 No.2: 俄亥俄州祭祀案',
    eventTime: '1968',
    location: '俄亥俄州 (Ohio)',
    keywords: ['俄亥俄州', '祭祀案', '伦德格兰'],
    people: ['伦德格兰 (Lundgren)', '莫宁 (Morning)'],
    summary: '关于1968年俄亥俄州柯特兰邪教屠杀案的供述。揭示了雷吉博士的"统一场论"与伦德格兰案件之间的联系。',
    status: 'DECRYPTED'
  },
  {
    id: 'confession_3',
    displayId: 'REC-1985-IL',
    title: '供述 No.3: 罗格·毕比失踪案',
    eventTime: '1985',
    location: '伊利诺伊州 (Illinois)',
    keywords: ['罗格·毕比', '1985'],
    people: ['罗格·毕比 (Roger Beebe)'],
    summary: '关于香槟镇失踪案真凶的供述。揭示了罗格·毕比在1985年落网后的供词，以及康查尔对此类"不受控恶行"的鄙夷态度。',
    status: 'DECRYPTED'
  },
  {
    id: 'confession_30',
    displayId: 'REC-1975-MT',
    title: '供述 No.30: 利比镇之约',
    eventTime: '1975',
    location: '蒙大拿州 (Montana)',
    keywords: ['利比镇', '什一税', '威廉·道森'],
    people: ['威廉·道森 (William Dawson)', '瓦妮莎 (Vanessa)'],
    summary: '关于瓦妮莎在红杉林中的深夜坦白。揭示了她与亚瑟·道森之间的契约，以及那个藏在生锈吊坠盒里的、通往利比镇的最后希望。',
    status: 'DECRYPTED'
  },
  {
    id: 'confession_4',
    displayId: 'REC-1967-NV',
    title: '供述 No.4: 训练日回忆',
    eventTime: '1967',
    location: '内华达州 (Nevada)',
    keywords: ['内华达州'],
    people: ['雷吉博士 (Dr. Reggie)'],
    summary: '关于特工选拔与训练结束时的关键对话。揭示了雷吉博士选中卡彭的真实原因——一种被视为"天赋"的精神病态特质。',
    status: 'DECRYPTED'
  },
  {
    id: 'confession_5',
    displayId: 'REC-1973-NV',
    title: '供述 No.5: 维恩灭门案',
    eventTime: '1973',
    location: '内华达州 (Nevada)',
    keywords: ['小德里克·维恩', '灭门案', '1971'],
    people: ['小德里克·维恩 (Derek Wayne Jr.)', '康查尔 (Conchar)'],
    summary: '关于维恩一家惨遭灭门的真相。揭示了该家族长子因其变态嗜好招致的报复，以及康查尔对此事所持的"受约束暴力"观点。',
    status: 'DECRYPTED'
  },
  {
    id: 'confession_6',
    displayId: 'REC-1972-VA',
    title: '供述 No.6: 灰水信标',
    eventTime: '1972',
    location: '弗吉尼亚州 (Virginia)',
    keywords: ['罗阿诺克市', '灰水信标', '铁马'],
    people: ['雷吉博士 (Dr. Reggie)', '康查尔 (Conchar)'],
    summary: '关于“信标”系统的建立与早期运作。揭示了康查尔在逃亡途中如何利用特定品牌烟盒向清理小组单向传递情报的全过程。',
    status: 'DECRYPTED'
  },
  {
    id: 'confession_7',
    displayId: 'REC-1972-VA-R',
    title: '供述 No.7: 罗阿诺克谋杀案',
    eventTime: '1972 ∙ 深秋',
    location: '弗吉尼亚州 罗阿诺克市 (Roanoke)',
    keywords: ['玛莎·迪亚兹', '莫布利', '罗阿诺克市'],
    people: ['康查尔 (Conchar)', '尼比 (Nibi)', '玛莎·迪亚兹 (Martha Diaz)'],
    summary: '关于康查尔与尼比之间病态关系的深度剖析，以及卡彭在罗阿诺克市的廉价旅馆中首次接触暴力仪式的经历。揭示了他目睹玛莎·迪亚兹被杀的全过程。',
    status: 'DECRYPTED'
  },
  {
    id: 'confession_8',
    displayId: 'REC-1973-KY',
    title: '供述 No.8: 路易斯维尔房车',
    eventTime: '1973 ∙ 正月',
    location: '肯塔基州 路易斯维尔 (Louisville)',
    keywords: ['1973', '朱莉'],
    people: ['父亲 (Father)', '康查尔 (Conchar)', '母亲 (The Mother)', '塞勒斯 (Silas)', '瓦妮莎 (Vanessa)'],
    summary: '关于卡彭首次进入"家族"核心的供述。揭示了1973年辛辛那提少女朱莉冻死案的真相，以及他在路易斯维尔码头首次见到"父亲"和淡蓝色房车内其他成员的经历。',
    status: 'DECRYPTED'
  },
  {
    id: 'confession_9',
    displayId: 'REC-1982-TX',
    title: '供述 No.9: 薄荷计划与灵魂厨房',
    eventTime: '1982 ∙ 深秋',
    location: '德克萨斯州 埃尔帕索 (El Paso)',
    keywords: ['1973', '朱维尔·钱伯斯', '远亲'],
    people: ['父亲 (Father)', '康查尔 (Conchar)', '朱维尔·钱伯斯 (Juvell Chambers)'],
    summary: '关于"灵魂厨房计划"的深度揭露。卡彭讲述了1982年在埃尔帕索投放最后一个信标的经历，以及1973年纳什维尔军械库窃案背后"家族"利用种族冲突掩护犯罪的真相。',
    status: 'DECRYPTED'
  },
  {
    id: 'confession_10',
    displayId: 'REC-1973-KY-B',
    title: '供述 No.10: 伯克斯维尔计划',
    eventTime: '1973 ∙ 深秋',
    location: '肯塔基州 伯克斯维尔 (Burkesville)',
    keywords: ['招募', '鲍里斯·斯米尔诺夫'],
    people: ['父亲 (Father)', '康查尔 (Conchar)', '塞勒斯 (Silas)', '母亲 (The Mother)', '鲍里斯·斯米尔诺夫 (Boris Smirnov)'],
    summary: '关于卡彭首次独立策划行动的供述。揭示了1973年在伯克斯维尔，"父亲"如何要求他为"远亲"设计计划，以及家族内部"先拆解再重塑"的招募方法和成员间的权力关系。',
    status: 'DECRYPTED'
  },
  {
    id: 'confession_11',
    displayId: 'REC-1975-KY-SS',
    title: '供述 No.11: 静态雪花计划',
    eventTime: '1975年前后',
    location: '肯塔基州 伯克斯维尔 (Burkesville)',
    keywords: ['KLUB-75报告', '匡提科', '静态雪花计划'],
    people: ['父亲 (Father)', '母亲 (The Mother)', '塞勒斯 (Silas)', '辛西娅·米勒 (Cynthia Miller)'],
    summary: '关于"静态雪花计划"的供述。揭示了卡彭如何利用FBI战术设计心理操控行动，通过拍摄"前卫艺术"录像绑架辛西娅·米勒，制造恐慌并享受破坏秩序的快感，完成从FBI探员到享受混乱的变态者的心理转变。',
    status: 'DECRYPTED'
  },
  {
    id: 'confession_12',
    displayId: 'REC-1976-MO',
    title: '供述 No.12: 流动献血车计划',
    eventTime: '1976',
    location: '堪萨斯城 (Kansas City)',
    keywords: ['堪萨斯城', '流动献血车', '1976', '杰西·潘尼'],
    people: ['罗伯特·卡彭 (Robert Capone)', '赛勒斯 (Silas)', '瓦妮莎 (Vanessa)'],
    summary: '关于1976年堪萨斯城"流动献血车"行动的供述。揭示了卡彭如何设计极其荒谬的超现实主义犯罪来拖延捕捕时间并渗透远亲网络，以及瓦妮莎对其人性转变的质问。',
    status: 'DECRYPTED'
  },
  {
    id: 'confession_13',
    displayId: 'REC-1976-MO-C',
    title: '供述 No.13: 混乱的美学',
    eventTime: '1976',
    location: '堪萨斯城 (Kansas City)',
    keywords: ['约翰·莫里西', '混乱美学', '1976'],
    people: ['父亲 (Father)', '罗伯特·卡彭 (Robert Capone)'],
    summary: '关于莫里西（杰西·潘尼）被捕后的对话揭密。揭示了"父亲"对"混乱"的独特哲学见解，以及卡彭如何通过制造混乱，在不经意间摧毁了连联邦政府都无法撼动的犯罪堡垒。',
    status: 'DECRYPTED'
  },
  {
    id: 'confession_14',
    displayId: 'REC-1976-SL',
    title: '供述 No.14: 圣路易斯之夜',
    eventTime: '1976',
    location: '密苏里州 圣路易斯市 (St. Louis)',
    keywords: ['圣路易斯', '蛆虫'],
    people: ['母亲 (The Mother)', '塞勒斯 (Silas)', '瓦妮莎 (Vanessa)'],
    summary: '关于堪萨斯城行动后，在圣路易斯市郊房车内发生的古老且极其令人不适的仪式。揭示了“母亲”与“父亲”之间通过鲜血构建的共生关系本质。',
    status: 'DECRYPTED'
  },
  {
    id: 'confession_15',
    displayId: 'REC-1976-IA',
    title: '供述 No.15: 达文波特静默屠杀',
    eventTime: '1976',
    location: '爱荷华州 达文波特市 (Davenport)',
    keywords: ['达文波特市', '新计划', '1976', '静默屠杀'],
    people: ['皮特·亨德森 (Peter Henderson)', '康查尔 (Conchar)', '罗伯特·卡彭 (Robert Capone)'],
    summary: '关于爱荷华州达文波特郊区亨德森一家灭门案的供述。康查尔以“新计划”为名，对一户普通中产家庭施加极端心理拷问，却在男主人皮特·亨德森拒绝成为“怪物”的选择面前首次感到挫败；这一刻也让卡彭在房车内重新想起自己身为警探的身份与使命。',
    status: 'DECRYPTED'
  },
  {
    id: 'confession_16',
    displayId: 'REC-1967-TX',
    title: '供述 No.16: 特克萨卡纳碎尸案',
    eventTime: '1967',
    location: '得克萨斯州 特克萨卡纳 (Texarkana)',
    keywords: ['特克萨卡纳', '碎尸案', '亚瑟·道森'],
    people: ['亚瑟·道森 (Arthur Dawson)', '康查尔 (Conchar)', '瓦妮莎 (Vanessa)'],
    summary: '关于1967年特克萨卡纳碎尸案的真相，以及卡彭从房车大梁下意外发现的亚瑟·道森笔记。揭示了亚瑟对“远亲”网络真实性的早期质疑，以及这种质疑如何导致了他的死亡。',
    status: 'DECRYPTED'
  },
  {
    id: 'confession_17',
    displayId: 'REC-1977-IL',
    title: '供述 No.17: 脏弗兰克酒吧与招募',
    eventTime: '1977年前后',
    location: '伊利诺伊州 罗克福德市 (Rockford)',
    keywords: ['脏弗兰克酒吧', '招募', '罗克福德市', '里奇·德莱弗斯'],
    people: ['里奇·德莱弗斯 (Richie Dreyfuss)', '康查尔 (Conchar)', '罗伯特·卡彭 (Robert Capone)'],
    summary: '关于里奇·德莱弗斯的招募背景及其死因的供述。描述了康查尔在罗克福德市的一间旅馆内设计的“俄罗斯轮盘”心理博弈，最终导致里奇因极度恐惧而自发性心脏衰竭。揭示了康查尔“恐惧才是唯一的子弹”这一极端哲学。',
    status: 'DECRYPTED'
  },
  {
    id: 'confession_18',
    displayId: 'REC-1974-UT',
    title: '供述 No.18: 警员遇害案与艾莉丝',
    eventTime: '1974 ∙ 秋',
    location: '犹他州 盐湖城郊外 (Utah)',
    keywords: ['丹佛市郊', '警员遇害案', '艾莉丝', '利伯勒尔', '冰锥'],
    people: ['艾莉丝 (Alice)', '康查尔 (Conchar)', '米勒副警长 (Deputy Miller)'],
    summary: '关于艾莉丝加入“家族”背景的供述。描述了她在丹佛市郊利伯勒尔镇对米勒副警长的残酷处决过程。揭示了艾莉丝作为该组织中真正“享受”杀戮的成员身份，以及她顺着血腥味横跨半个美国寻找罗伯特的惊人执念。',
    status: 'DECRYPTED'
  },
  {
    id: 'confession_19',
    displayId: 'REC-1974-TX',
    title: '供述 No.19: 埃尔帕索教堂屠杀',
    eventTime: '1974',
    location: '德克萨斯州 埃尔帕索 (El Paso)',
    keywords: ['埃尔帕索', '神父', '教堂', '1974', '猎枪'],
    people: ['神父 (The Priest)', '康查尔 (Conchar)', '塞勒斯 (Silas)'],
    summary: '关于埃尔帕索教堂惨案的供述。揭示了康查尔如何利用种族仇恨煽动一起针对边境教堂的袭击，以及那名所谓“沉默的神父”在死亡面前展现出的、令康查尔感到不安的平静。',
    status: 'DECRYPTED'
  },
  {
    id: 'confession_20',
    displayId: 'REC-1978-NV',
    title: '供述 No.20: 80号洲际公路守夜人',
    eventTime: '1978',
    location: '内华达州 80号洲际公路 (I-80)',
    keywords: ['80号洲际公路', '守夜人', '无线电', '卡车司机'],
    people: ['罗伯特·卡彭 (Robert Capone)', '守夜人 (The Watchman)'],
    summary: '关于在80号公路上遇到的神秘卡车司机“守夜人”的供述。这实际上是卡彭分裂人格的早期具象化体现，他在无线电中与另一个自己对话，预示着他最终精神崩溃的开端。',
    status: 'DECRYPTED'
  },
  {
    id: 'confession_21',
    displayId: 'REC-1951-KR',
    title: '供述 No.21: 亚玛力人协议',
    eventTime: '1951 / 1968',
    location: '梅诺西诺 (Mendocino) / 巨济岛 (Geoje-do)',
    keywords: ['波特兰', '软肋', '红杉林', '战俘营', '亚玛力人协议'],
    people: ['父亲 (Father)', '雷吉博士 (Dr. Reggie)', '塞勒斯 (Silas)', '艾莉丝 (Alice)'],
    summary: '关于“父亲”权威来源的终极解密。揭示了他在朝鲜战争巨济岛战俘营的经历，以及他如何将美军心理战技术转化为控制“家族”的洗脑工具（亚玛力人协议），并以此策划了针对嬉皮士的假旗行动。',
    status: 'DECRYPTED'
  },
  {
    id: 'confession_22',
    displayId: 'REC-1975-CA',
    title: '供述 No.22: 圣芭芭拉收网',
    eventTime: '1975',
    location: '加利福尼亚州 圣芭芭拉 (Santa Barbara)',
    keywords: ['红杉林', '战俘营', '圣芭芭拉', '收网', '什一税'],
    people: ['罗伯特·卡彭 (Robert Capone)', '瓦妮莎 (Vanessa)', '父亲 (Father)', '康查尔 (Conchar)'],
    summary: '关于卡彭在房车夹层发现真相并决定收网的关键转折点。揭示了瓦妮莎试图策反他的失败尝试，以及他在发现父亲利用房车车顶夹层伪造“神谕”和生产宣传品后，决心将其逮捕的心理决断。',
    status: 'DECRYPTED'
  },
  {
    id: 'confession_23',
    displayId: 'REC-1975-CA-B',
    title: '供述 No.23: 裸根行动与误判',
    eventTime: '1975',
    location: '加利福尼亚州 圣芭芭拉 (Santa Barbara)',
    keywords: ['拉古那海滩', '裸根', '阿列克谢·罗科维奇', '瓦妮莎'],
    people: ['罗伯特·卡彭 (Robert Capone)', '艾莉丝 (Alice)', '阿列克谢 (Alexei)', '塞勒斯 (Silas)'],
    summary: '关于针对苏联情报站负责人阿列克谢·罗科维奇的静默清洗行动。揭示了艾莉丝为了确保行动成功和掩盖行踪，不惜炸死自己的情人兼棋子塞勒斯，并将阿列克谢焚尸灭迹，导致原本的渗透任务升级为"恐怖袭击"，迫使"父亲"不得不更加激进地利用手中的筹码。',
    status: 'DECRYPTED'
  },
  {
    id: 'confession_24',
    displayId: 'REC-1975-LB',
    title: '供述 No.24: 化学家情人与大法官',
    eventTime: '1975',
    location: '加利福尼亚州 拉古那海滩 (Laguna Beach)',
    keywords: ['莫兰迪', '阿尔伯克基市', '化学家情人'],
    people: ['父亲 (Father)', '艾莉丝 (Alice)', '瓦妮莎 (Vanessa)', '索恩法官 (Judge Thorne)', '莫兰迪 (Morandi)'],
    summary: '关于利用"裸根"名单控制联邦大法官肯尼迪·索恩的供述。描述了艾莉丝如何利用她的旧情人"莫兰迪"（阿尔伯克基爆炸案主犯）作为诱饵，以及父亲如何通过残酷的手段（给瓦妮莎注射士的宁）来取悦并控制这位变态法官，从而接管了KGB对司法系统的渗透网络。',
    status: 'DECRYPTED'
  },
  {
    id: 'confession_25',
    displayId: 'REC-1975-NM',
    title: '供述 No.25: 邦妮和克莱德',
    eventTime: '1975',
    location: '新墨西哥州 阿尔伯克基 (Albuquerque)',
    keywords: ['圣菲', '邦妮和克莱德'],
    people: ['罗伯特·卡彭 (Robert Capone)', '艾莉丝 (Alice)', '莫兰迪 (Morandi)'],
    summary: '关于前往新墨西哥州接收高能炸药的途中经历。揭示了卡彭与艾莉丝在逃亡与服从之间的一念之差，以及艾莉丝对卡彭内心"精神病态"特质的精准洞察与诱导。',
    status: 'DECRYPTED'
  },
  {
    id: 'confession_26',
    displayId: 'REC-1976-AZ',
    title: '供述 No.26: 最后的押送',
    eventTime: '1976',
    location: '亚利桑那州 (Arizona)',
    keywords: ['圣菲', '邦妮和克莱德'],
    people: ['罗伯特·卡彭 (Robert Capone)', '父亲 (Father)', '母亲 (Mother)', '艾莉丝 (Alice)', '瓦妮莎 (Vanessa)'],
    summary: '卡彭潜伏生涯的终结之战。描述了他如何巧妙利用瓦妮莎和莫兰迪的冲突调开同伙，并在荒漠公路上亲手处决“母亲”并完全控制了“父亲”。这是一次彻底的人格断裂与重组。',
    status: 'DECRYPTED'
  },
  {
    id: 'confession_27',
    displayId: 'REC-1976-MV',
    title: '供述 No.27: 米尔谷的礼物',
    eventTime: '1976 ∙ 晚秋',
    location: '加利福尼亚州 米尔谷 (Mill Valley)',
    keywords: ['莫兰迪', '米尔谷', '礼物', '1976', '迟摘特酿'],
    people: ['莫兰迪 (Morandi)', '艾莉丝 (Alice)', '父亲 (Father)', '罗伯特·卡彭 (Robert Capone)'],
    summary: '关于1976年米尔谷针对某位记者的长期爆炸计划供述。莫兰迪利用“重力是不朽的”这一冷酷哲学，在地基中安置了通过沥青缓慢下滴触发的炸药。这不仅是一次犯罪，更是一场关于时间、恶意与“迟摘特酿”美学的病态展示。',
    status: 'DECRYPTED'
  },
  {
    id: 'confession_28',
    displayId: 'REC-1976-LB',
    title: '供述 No.28: 拉古那海滩的清道夫',
    eventTime: '1976 ∙ 冬',
    location: '加利福尼亚州 拉古那海滩 (Laguna Beach)',
    keywords: ['拉古那海滩', '戈尔和列维探员'],
    people: ['罗伯特·卡彭 (Robert Capone)', '艾莉丝 (Alice)', '戈尔和列维探员 (Agents Gore & Levy)'],
    summary: '关于在拉古那海滩反杀两名监视房车的联邦调查局探员的供述。揭示了卡彭如何单枪匹马处理掉戈尔和列维探员，并利用防弹监视车将尸体沉入海沟。这也引出了关于谁在暗中泄露行踪的更深层疑云。',
    status: 'DECRYPTED'
  },
  {
    id: 'confession_29',
    displayId: 'REC-1975-OR',
    title: '供述 No.29: 红杉林深处',
    eventTime: '1975',
    location: '俄勒冈州 (Oregon)',
    keywords: ['林地深处', '亚玛力人协议', '费利佩·马尔多纳多', 'FELIPE MALDONADO'],
    people: ['费利佩·马尔多纳多 (Felipe Maldonado)', '瓦妮莎 (Vanessa)', '艾莉丝 (Alice)'],
    summary: '关于1975年发生在俄勒冈红杉林中的惨案。揭示了瓦妮莎对自由的渴望，以及艾莉丝如何以一种极其残酷的方式“满足”了这种渴望——带回了一张带血的费利佩·马尔多纳多演出海报。',
    status: 'DECRYPTED'
  },
  {
    id: 'confession_31',
    displayId: 'REC-1967-ME',
    title: '供述 No.31: 汉弗莱监狱与袭警案',
    eventTime: '1967',
    location: '缅因州 汉弗莱县 (Humphrey County)',
    keywords: ['汉弗莱县', '袭警案'],
    people: ['康查尔 (Conchar)', '罗伯特·卡彭 (Robert Capone)'],
    summary: '关于在缅因州汉弗莱监狱认识康查尔（即弗兰克·罗林斯）以及他因袭警入狱背景的供述。揭示了这段关系的起始，以及康查尔作为刺头新人的危险特征。',
    status: 'DECRYPTED'
  },
  {
    id: 'confession_32',
    displayId: 'REC-1967-ND',
    title: '供述 No.32: 曼丹市的房车',
    eventTime: '1967',
    location: '北达科他州 曼丹市 (Mandan)',
    keywords: ['曼丹市', '森林地图'],
    people: ['康查尔 (Conchar)', '瓦妮莎 (Vanessa)', '父亲 (Father)', '罗伯特·卡彭 (Robert Capone)'],
    summary: '关于曼丹市青少年矫正机构接送瓦妮莎及康查尔入狱背后的真相供述。解开了康查尔入狱其实是父亲为隔离瓦妮莎并维持其“清白感”而精心策划的圈套，同时也标志着卡彭对家族谎言网的进一步拆解。',
    status: 'DECRYPTED'
  },
  {
    id: 'confession_33',
    displayId: 'REC-1983-AZ',
    title: '供述 No.33: 1983年通缉令',
    eventTime: '1983',
    location: '亚利桑那州 (Arizona)',
    keywords: ['第4警务站', '图森枪击案', '1983', '通缉令'],
    people: ['罗伯特·卡彭 (Robert Capone)', '艾莉丝 (Alice)'],
    summary: '关于1983年在奥德赛邮局发现自己通缉令的供述。揭示了卡彭在图森枪杀案后的逃亡生涯，以及艾莉丝通过通缉令向他传递的某种隐秘讯息。',
    status: 'DECRYPTED'
  }
];
